version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      args:
        - NEXT_PUBLIC_SERVER_URL=http://localhost:8000  # Use service name instead of localhost
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://localhost:8000  # Use backend service name
    networks:
      - app_network

  backend:
    build: ../backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
      - MONGO_URI=mongodb://mongo:27017/mydatabase  # No authentication required
    networks:
      - app_network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongo_data:
